version: '3.8'

services:
  temporal:
    image: temporal_lite:latest
    build:
      context: .
      dockerfile: ./temporal.dockerfile
    restart: always
    ports:
      - "7233:7233"
      - "8233:8233"
  postgres:
    image: postgres:17
    environment:
      POSTGRES_DB: workflows
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports: [ "5432:5432" ]