// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.7
// 	protoc        v5.28.2
// source: proto/workflow.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type StartReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	WorkflowId    string                 `protobuf:"bytes,1,opt,name=workflow_id,json=workflowId,proto3" json:"workflow_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StartReq) Reset() {
	*x = StartReq{}
	mi := &file_proto_workflow_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StartReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartReq) ProtoMessage() {}

func (x *StartReq) ProtoReflect() protoreflect.Message {
	mi := &file_proto_workflow_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartReq.ProtoReflect.Descriptor instead.
func (*StartReq) Descriptor() ([]byte, []int) {
	return file_proto_workflow_proto_rawDescGZIP(), []int{0}
}

func (x *StartReq) GetWorkflowId() string {
	if x != nil {
		return x.WorkflowId
	}
	return ""
}

type StartResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	WorkflowId    string                 `protobuf:"bytes,1,opt,name=workflow_id,json=workflowId,proto3" json:"workflow_id,omitempty"`
	RunId         string                 `protobuf:"bytes,2,opt,name=run_id,json=runId,proto3" json:"run_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StartResp) Reset() {
	*x = StartResp{}
	mi := &file_proto_workflow_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StartResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartResp) ProtoMessage() {}

func (x *StartResp) ProtoReflect() protoreflect.Message {
	mi := &file_proto_workflow_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartResp.ProtoReflect.Descriptor instead.
func (*StartResp) Descriptor() ([]byte, []int) {
	return file_proto_workflow_proto_rawDescGZIP(), []int{1}
}

func (x *StartResp) GetWorkflowId() string {
	if x != nil {
		return x.WorkflowId
	}
	return ""
}

func (x *StartResp) GetRunId() string {
	if x != nil {
		return x.RunId
	}
	return ""
}

type StatusReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	WorkflowId    string                 `protobuf:"bytes,1,opt,name=workflow_id,json=workflowId,proto3" json:"workflow_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StatusReq) Reset() {
	*x = StatusReq{}
	mi := &file_proto_workflow_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StatusReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatusReq) ProtoMessage() {}

func (x *StatusReq) ProtoReflect() protoreflect.Message {
	mi := &file_proto_workflow_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatusReq.ProtoReflect.Descriptor instead.
func (*StatusReq) Descriptor() ([]byte, []int) {
	return file_proto_workflow_proto_rawDescGZIP(), []int{2}
}

func (x *StatusReq) GetWorkflowId() string {
	if x != nil {
		return x.WorkflowId
	}
	return ""
}

type StatusResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	WorkflowId    string                 `protobuf:"bytes,1,opt,name=workflow_id,json=workflowId,proto3" json:"workflow_id,omitempty"`
	Status        string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StatusResp) Reset() {
	*x = StatusResp{}
	mi := &file_proto_workflow_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StatusResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatusResp) ProtoMessage() {}

func (x *StatusResp) ProtoReflect() protoreflect.Message {
	mi := &file_proto_workflow_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatusResp.ProtoReflect.Descriptor instead.
func (*StatusResp) Descriptor() ([]byte, []int) {
	return file_proto_workflow_proto_rawDescGZIP(), []int{3}
}

func (x *StatusResp) GetWorkflowId() string {
	if x != nil {
		return x.WorkflowId
	}
	return ""
}

func (x *StatusResp) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

var File_proto_workflow_proto protoreflect.FileDescriptor

const file_proto_workflow_proto_rawDesc = "" +
	"\n" +
	"\x14proto/workflow.proto\x12\bworkflow\"+\n" +
	"\bStartReq\x12\x1f\n" +
	"\vworkflow_id\x18\x01 \x01(\tR\n" +
	"workflowId\"C\n" +
	"\tStartResp\x12\x1f\n" +
	"\vworkflow_id\x18\x01 \x01(\tR\n" +
	"workflowId\x12\x15\n" +
	"\x06run_id\x18\x02 \x01(\tR\x05runId\",\n" +
	"\tStatusReq\x12\x1f\n" +
	"\vworkflow_id\x18\x01 \x01(\tR\n" +
	"workflowId\"E\n" +
	"\n" +
	"StatusResp\x12\x1f\n" +
	"\vworkflow_id\x18\x01 \x01(\tR\n" +
	"workflowId\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status2\x83\x01\n" +
	"\x0fWorkflowService\x128\n" +
	"\rStartWorkflow\x12\x12.workflow.StartReq\x1a\x13.workflow.StartResp\x126\n" +
	"\tGetStatus\x12\x13.workflow.StatusReq\x1a\x14.workflow.StatusRespB/Z-github.com/you/workflow-runner/internal/pb;pbb\x06proto3"

var (
	file_proto_workflow_proto_rawDescOnce sync.Once
	file_proto_workflow_proto_rawDescData []byte
)

func file_proto_workflow_proto_rawDescGZIP() []byte {
	file_proto_workflow_proto_rawDescOnce.Do(func() {
		file_proto_workflow_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_workflow_proto_rawDesc), len(file_proto_workflow_proto_rawDesc)))
	})
	return file_proto_workflow_proto_rawDescData
}

var file_proto_workflow_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_proto_workflow_proto_goTypes = []any{
	(*StartReq)(nil),   // 0: workflow.StartReq
	(*StartResp)(nil),  // 1: workflow.StartResp
	(*StatusReq)(nil),  // 2: workflow.StatusReq
	(*StatusResp)(nil), // 3: workflow.StatusResp
}
var file_proto_workflow_proto_depIdxs = []int32{
	0, // 0: workflow.WorkflowService.StartWorkflow:input_type -> workflow.StartReq
	2, // 1: workflow.WorkflowService.GetStatus:input_type -> workflow.StatusReq
	1, // 2: workflow.WorkflowService.StartWorkflow:output_type -> workflow.StartResp
	3, // 3: workflow.WorkflowService.GetStatus:output_type -> workflow.StatusResp
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_workflow_proto_init() }
func file_proto_workflow_proto_init() {
	if File_proto_workflow_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_workflow_proto_rawDesc), len(file_proto_workflow_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_workflow_proto_goTypes,
		DependencyIndexes: file_proto_workflow_proto_depIdxs,
		MessageInfos:      file_proto_workflow_proto_msgTypes,
	}.Build()
	File_proto_workflow_proto = out.File
	file_proto_workflow_proto_goTypes = nil
	file_proto_workflow_proto_depIdxs = nil
}
